import { useEffect, useMemo, useState } from 'react'
import {
  createSecondSightApi,
  type AlertRecord,
  type SecondSightApi,
} from './api'

interface AlertsPageProps {
  api?: SecondSightApi
  sessionId?: string
}

function AlertsPage({ api, sessionId }: AlertsPageProps) {
  const environment = import.meta.env
  const configuredApi = useMemo(() => api ?? createSecondSightApi({
    supabaseUrl: environment.VITE_SUPABASE_URL ?? '',
    supabaseAnonKey: environment.VITE_SUPABASE_ANON_KEY ?? '',
  }), [api, environment.VITE_SUPABASE_ANON_KEY, environment.VITE_SUPABASE_URL])
  const resolvedSessionId = sessionId ?? new URLSearchParams(window.location.search)
    .get('session_id')?.trim() ?? ''
  const [alerts, setAlerts] = useState<AlertRecord[]>([])
  const [loading, setLoading] = useState(resolvedSessionId.length > 0)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!resolvedSessionId) return
    let isActive = true
    configuredApi.listAlerts(resolvedSessionId)
      .then((records) => {
        if (isActive) setAlerts(records)
      })
      .catch(() => {
        if (isActive) setError('Unable to load the alert history. Please try again shortly.')
      })
      .finally(() => {
        if (isActive) setLoading(false)
      })
    return () => { isActive = false }
  }, [configuredApi, resolvedSessionId])

  return (
    <div className="alerts-shell">
      <header className="alerts-header">
        <a href="/" aria-label="Back to Volunteer Console">← Back to Volunteer Console</a>
        <span>SecondSight · Traceable by Design</span>
      </header>
      <main className="alerts-main">
        <p className="eyebrow">SESSION SAFETY AUDIT</p>
        <h1>Safety Alert History</h1>
        <p className="alerts-intro">Only alerts and session pauses generated by the AI safety monitor are shown.</p>

        {!resolvedSessionId && <p role="alert">Session ID is missing. Open the alert history from the assistance page.</p>}
        {loading && <p role="status">Loading safety alerts…</p>}
        {error && <p className="form-error" role="alert">{error}</p>}
        {!loading && !error && resolvedSessionId && alerts.length === 0 && (
          <p className="alerts-empty">No safety alerts have been recorded for this session.</p>
        )}
        <ol className="alerts-list">
          {alerts.map((alert) => (
            <li className={`alert-card alert-card--${alert.severity}`} key={alert.id}>
              <div className="alert-card__meta">
                <strong>{alert.severity === 'freeze' ? 'Session Paused' : 'Safety Alert'}</strong>
                <time dateTime={alert.timestamp}>{formatTimestamp(alert.timestamp)}</time>
              </div>
              <h2>{alert.reason}</h2>
              <p>{alert.transcript}</p>
            </li>
          ))}
        </ol>
      </main>
    </div>
  )
}

function formatTimestamp(value: string): string {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return new Intl.DateTimeFormat('en-AU', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date)
}

export default AlertsPage
